version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./src/test/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  mysql:
    image: mysql:8.0.34
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - ./src/test/resources/schema-mysql.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
